---
# Copyright (c) 2017 F5 Networks Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
- name: Manage active-standby licensed TMOS VE device pair
  os_stack:
      name: "{{ stack_name }}"
      state: "{{ state }}"
      template: "{{ template_path }}"
      parameters: {}
      environment:
        - "{{ env_file_path }}"
      timeout: 1800
      wait: yes
      auth:
        auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
        username: "{{ lookup('env','OS_USERNAME') }}"
        password: "{{ lookup('env','OS_PASSWORD') }}"
        project_name: "{{ lookup('env','OS_PROJECT_NAME') }}"
  register: f5_bigip_deployment

- set_fact:
    bigip_icontrol_endpoint_slave: "{{ result[0].output_value }}"
  vars:
    query: "[?output_key=='floating_ip_slave']"
    result: "{{ f5_bigip_deployment.stack.outputs | json_query(query) }}"
  when:
    - state != "absent"

- set_fact:
    data_int_slave: "{{ result[0].output_value }}"
  vars:
    query: "[?output_key=='data_fixed_ips_slave']"
    result: "{{ f5_bigip_deployment.stack.outputs | json_query(query) }}"
  when:
    - state != "absent"

- set_fact:
    data_1_1_slave: "{{ data_int_slave[0] }}"
  when:
    - state != "absent"

- set_fact:
    data_1_2_slave: "{{ data_int_slave[1] }}"
  when:
    - state != "absent"

- set_fact:
    data_1_3_slave: "{{ data_int_slave[2] }}"
  when:
    - state != "absent"

- set_fact:
    data_1_4_slave: "{{ data_int_slave[3] }}"
  when:
    - state != "absent"

- set_fact:
    bigip_icontrol_endpoint_master: "{{ result[0].output_value }}"
  vars:
    query: "[?output_key=='floating_ip_master']"
    result: "{{ f5_bigip_deployment.stack.outputs | json_query(query) }}"
  when:
    - state != "absent"

- set_fact:
    data_int_master: "{{ result[0].output_value }}"
  vars:
    query: "[?output_key=='data_fixed_ips_master']"
    result: "{{ f5_bigip_deployment.stack.outputs | json_query(query) }}"
  when:
    - state != "absent"

- set_fact:
    data_1_1_master: "{{ data_int_master[0] }}"
  when:
    - state != "absent"

- set_fact:
    data_1_2_master: "{{ data_int_master[1] }}"
  when:
    - state != "absent"

- set_fact:
    data_1_3_master: "{{ data_int_master[2] }}"
  when:
    - state != "absent"

- set_fact:
    data_1_4_master: "{{ data_int_master[3] }}"
  when:
    - state != "absent"

- name: iControl Endpoint for Active Device
  debug: var=bigip_icontrol_endpoint_slave
  when:
    - state != "absent"

- name: iControl Endpoint for Standby Device
  debug: var=bigip_icontrol_endpoint_master
  when:
    - state != "absent"

- name: Active Interface 1.1 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_1_slave }}"
  when:
    - state != "absent"

- name: Standby Interface 1.1 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_1_master }}"
  when:
    - state != "absent"

- name: Active Interface 1.2 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_2_slave }}"
  when:
    - state != "absent"
    
- name: Standby Interface 1.2 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_2_master }}"
  when:
    - state != "absent"

- name: Active Interface 1.3 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_3_slave }}"
  when:
    - state != "absent"

- name: Standby Interface 1.3 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_3_master }}"
  when:
    - state != "absent"

- name: Active Interface 1.4 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_4_slave }}"
  when:
    - state != "absent"

- name: Standby Interface 1.4 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_4_master }}"
  when:
    - state != "absent"

