---
# defaults file for standalone_stack_deploy
state: present
stack_name: standalone_stack_from_ansible
template_path: /data/project/f5-hot-ansible/roles/common/templates/f5-openstack-hot/experimental/reference/templates/standalone/nnic/f5_bigip_standalone_n_nic_licensed.yaml
env_file_path: /data/project/f5-hot-ansible/roles/common/templates/f5-openstack-hot/experimental/reference/templates/standalone/nnic/f5_bigip_standalone_n_nic_env_sl_licensed.yaml
