---
# Copyright (c) 2017 F5 Networks Inc.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
- name: Manage standalone licensed TMOS VE device
  os_stack:
      name: "{{ stack_name }}"
      state: "{{ state }}"
      template: "{{ template_path }}"
      parameters: {}
      environment:
        - "{{ env_file_path }}"
      timeout: 1800
      wait: yes
      auth:
        auth_url: "{{ lookup('env','OS_AUTH_URL') }}"
        username: "{{ lookup('env','OS_USERNAME') }}"
        password: "{{ lookup('env','OS_PASSWORD') }}"
        project_name: "{{ lookup('env','OS_PROJECT_NAME') }}"
  register: f5_bigip_deployment

- set_fact:
    bigip_icontrol_endpoint: "{{ result[0].output_value }}"
  vars:
    query: "[?output_key=='floating_ip']"
    result: "{{ f5_bigip_deployment.stack.outputs | json_query(query) }}"
  when:
    - state != "absent"

- set_fact:
    data_int: "{{ result[0].output_value }}"
  vars:
    query: "[?output_key=='data_fixed_ips']"
    result: "{{ f5_bigip_deployment.stack.outputs | json_query(query) }}"
  when:
    - state != "absent"

- set_fact:
    data_1_1: "{{ data_int[0] }}"
  when:
    - state != "absent"

- set_fact:
    data_1_2: "{{ data_int[1] }}"
  when:
    - state != "absent"

- set_fact:
    data_1_3: "{{ data_int[2] }}"
  when:
    - state != "absent"

- set_fact:
    data_1_4: "{{ data_int[3] }}"
  when:
    - state != "absent"

- name: iControl Endpoint
  debug: var=bigip_icontrol_endpoint
  when:
    - state != "absent"

- name: Interface 1.1 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_1 }}"
  when:
    - state != "absent"
    
- name: Interface 1.2 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_2 }}"
  when:
    - state != "absent"

- name: Interface 1.3 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_3 }}"
  when:
    - state != "absent"

- name: Interface 1.4 IP Address Allocations
  debug: var=item.ip_address
  with_items: "{{ data_1_4 }}"
  when:
    - state != "absent"

